<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Sender</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- Official Azure SDK package for talking to Service Bus (queues, topics/subscriptions) -->
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.18.2" />
  </ItemGroup>

</Project>
