<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SimpleBrokeredMessaging.ChatConsole</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- ServiceBusAdministrationClient lives in this same package, under Azure.Messaging.ServiceBus.Administration -->
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.18.2" />
  </ItemGroup>

</Project>
